name: Validate Agent PR

on:
  pull_request:
    paths:
      - 'agents/**.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for proper diff

    - name: Set up uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v41
      with:
        files: |
          agents/**.json
        json: true

    - name: Validate changed agent files
      id: validate
      run: |
        echo "🔍 Validating agent submissions..."

        # Parse the JSON array of changed files
        changed_files='${{ steps.changed-files.outputs.all_changed_files }}'

        # Convert JSON array to space-separated list
        # The output from changed-files action comes with escaped quotes, so we need to unescape first
        files=$(echo "$changed_files" | sed 's/\\\"/"/g' | jq -r '.[]' | tr '\n' ' ')

        if [ -z "$files" ]; then
          echo "No agent files changed"
          exit 0
        fi

        validation_failed=false

        for file in $files; do
          echo ""
          echo "Validating: $file"
          echo "----------------------------------------"

          if uv run python scripts/validate_agent.py "$file"; then
            echo "✅ $file passed validation"
          else
            echo "❌ $file failed validation"
            validation_failed=true
          fi
        done

        if [ "$validation_failed" = true ]; then
          echo ""
          echo "❌ One or more agent files failed validation"
          exit 1
        else
          echo ""
          echo "✅ All agent files passed validation!"
        fi

    - name: Save validation result
      if: always()
      run: |
        mkdir -p ./pr-comment
        echo "${{ github.event.pull_request.number }}" > ./pr-comment/pr-number
        if [ "${{ steps.validate.outcome }}" == "success" ]; then
          echo "success" > ./pr-comment/status
        else
          echo "failure" > ./pr-comment/status
        fi

    - name: Upload result artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pr-comment-data
        path: pr-comment/
